### ISSUE TITLE
angularjs as depency in bower.json file incorrect?

### ISSUE THREAD

**Issue by RonB** [jettro/c3-angular-sample#9]
I' m having an issue with the depency to angular**js**: ' ~ 1.3.8', as stated in the bower.json file.
All other pacakges are using angular, not angular**js**. Am I missing something here?

**Comment by jettro** [comment]
I am not sure, I see what you mean. But I cleaned my repo and did a bower install and everything seems to work. If I check the package.json of angularjs I also see that the name is angularjs, so I think it is fine. Can you elaborate a bit more what your problem is?

https://github.com/angular/angular.js/blob/master/package.json

thanks

**Comment by RonB** [comment]
Thanks for your response. 
The problem is that when i run bower install with c3-angular installed it installs a second version of angular, with the name angularjs. Because i use wiredep in my grunt file it adds the angular lib twice.

My current angular installation has a package.json :
{
  "name": "angular",
  "version": "1.3.12",
  "description": "HTML enhanced for web apps",
  "main": "angular.js",
....

**Comment by jettro** [comment]
I get it, checked the bower repository and noticed there that they have the same dependency as you mention. I have corrected it and made a new release 1.2.1. Can you verify if this is ok?

**Comment by RonB** [comment]
Works perfect now. Thank you.
